---
language: python
python: "3.6"
sudo: required
addons:
  apt:
    packages:
      - python-pip
install:
  - pip install ansible molecule molecule-docker
  - molecule --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
